/* Default config.h generated by Makefile */
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 600
#endif
#define HAVE_LIBBZ2 1
#define HAVE_LIBLZMA 1
#ifndef __APPLE__
#define HAVE_LZMA_H 1
#endif
#define HAVE_DRAND48 1
#define HAVE_LIBCURL 1
#define HAVE_DECL___CPUID_COUNT 1
#define HAVE_DECL___GET_CPUID_MAX 1
#define HAVE_POPCNT 1
#define HAVE_SSE4_1 1
#define HAVE_SSSE3 1
#if defined(HTS_ALLOW_UNALIGNED) && HTS_ALLOW_UNALIGNED == 0
#define UBSAN 1
#endif
#define HAVE_AVX2 1
#define HAVE_AVX512 1
#if defined __x86_64__ || defined __arm__ || defined __aarch64__
#define HAVE_ATTRIBUTE_CONSTRUCTOR 1
#endif
#if (defined(__x86_64__) || defined(_M_X64))
#define HAVE_ATTRIBUTE_TARGET 1
#define HAVE_BUILTIN_CPU_SUPPORT_SSSE3 1
#endif
