# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fetch a sequence region from a FASTA file using htslib faidx
#'
#' @param fasta_path Path to the FASTA file
#' @param seqname Chromosome/contig name (e.g., "chr1")
#' @param start 1-based start position (inclusive)
#' @param end 1-based end position (inclusive)
#' @return Character vector of the fetched sequence
#' @export
faidx_fetch_region <- function(fasta_path, seqname, start, end) {
    .Call(`_bcflib_faidx_fetch_region`, fasta_path, seqname, start, end)
}

#' Index a FASTA file using htslib faidx and return the index path
#'
#' @param fasta_path Path to the FASTA file
#' @return Path to the generated .fai index file
#' @export
faidx_index_fasta <- function(fasta_path) {
    .Call(`_bcflib_faidx_index_fasta`, fasta_path)
}

#'
#'
#' @export
heterozygosity <- function(vcffile, region = "", samples = "") {
    .Call(`_bcflib_heterozygosity`, vcffile, region, samples)
}

#'
#'
#' @export
getVariantInfo <- function(vcffile, region = "", samples = "") {
    .Call(`_bcflib_getVariantInfo`, vcffile, region, samples)
}

