# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#'
#' @export
heterozygosity <- function(vcffile, region = "", samples = "") {
    .Call(`_bcflib_heterozygosity`, vcffile, region, samples)
}

#'
#'
#' @export
getVariantInfo <- function(vcffile, region = "", samples = "") {
    .Call(`_bcflib_getVariantInfo`, vcffile, region, samples)
}

